# Generated by Django 5.0.6 on 2024-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_stud', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
